// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/ingestion.proto

package ingestionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerDataImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileReference string                 `protobuf:"bytes,1,opt,name=file_reference,json=fileReference,proto3" json:"file_reference,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDataImportRequest) Reset() {
	*x = TriggerDataImportRequest{}
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDataImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDataImportRequest) ProtoMessage() {}

func (x *TriggerDataImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDataImportRequest.ProtoReflect.Descriptor instead.
func (*TriggerDataImportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerDataImportRequest) GetFileReference() string {
	if x != nil {
		return x.FileReference
	}
	return ""
}

func (x *TriggerDataImportRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

type TriggerDataImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	InsertedRows  int32                  `protobuf:"varint,2,opt,name=inserted_rows,json=insertedRows,proto3" json:"inserted_rows,omitempty"`
	Errors        []*ImportError         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDataImportResponse) Reset() {
	*x = TriggerDataImportResponse{}
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDataImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDataImportResponse) ProtoMessage() {}

func (x *TriggerDataImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDataImportResponse.ProtoReflect.Descriptor instead.
func (*TriggerDataImportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerDataImportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerDataImportResponse) GetInsertedRows() int32 {
	if x != nil {
		return x.InsertedRows
	}
	return 0
}

func (x *TriggerDataImportResponse) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ImportError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowNumber     int32                  `protobuf:"varint,1,opt,name=row_number,json=rowNumber,proto3" json:"row_number,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *ImportError) GetRowNumber() int32 {
	if x != nil {
		return x.RowNumber
	}
	return 0
}

func (x *ImportError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_proto_v1_ingestion_proto protoreflect.FileDescriptor

const file_api_proto_v1_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/ingestion.proto\x12\x16stuko.api.v1.ingestion\"b\n" +
	"\x18TriggerDataImportRequest\x12%\n" +
	"\x0efile_reference\x18\x01 \x01(\tR\rfileReference\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\"\x97\x01\n" +
	"\x19TriggerDataImportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rinserted_rows\x18\x02 \x01(\x05R\finsertedRows\x12;\n" +
	"\x06errors\x18\x03 \x03(\v2#.stuko.api.v1.ingestion.ImportErrorR\x06errors\"Q\n" +
	"\vImportError\x12\x1d\n" +
	"\n" +
	"row_number\x18\x01 \x01(\x05R\trowNumber\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x8c\x01\n" +
	"\x10IngestionService\x12x\n" +
	"\x11TriggerDataImport\x120.stuko.api.v1.ingestion.TriggerDataImportRequest\x1a1.stuko.api.v1.ingestion.TriggerDataImportResponseBIZGgithub.com/vinosPASI/vinos/backend/api/proto/v1/ingestionpb;ingestionpbb\x06proto3"

var (
	file_api_proto_v1_ingestion_proto_rawDescOnce sync.Once
	file_api_proto_v1_ingestion_proto_rawDescData []byte
)

func file_api_proto_v1_ingestion_proto_rawDescGZIP() []byte {
	file_api_proto_v1_ingestion_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_ingestion_proto_rawDesc), len(file_api_proto_v1_ingestion_proto_rawDesc)))
	})
	return file_api_proto_v1_ingestion_proto_rawDescData
}

var file_api_proto_v1_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1_ingestion_proto_goTypes = []any{
	(*TriggerDataImportRequest)(nil),  // 0: stuko.api.v1.ingestion.TriggerDataImportRequest
	(*TriggerDataImportResponse)(nil), // 1: stuko.api.v1.ingestion.TriggerDataImportResponse
	(*ImportError)(nil),               // 2: stuko.api.v1.ingestion.ImportError
}
var file_api_proto_v1_ingestion_proto_depIdxs = []int32{
	2, // 0: stuko.api.v1.ingestion.TriggerDataImportResponse.errors:type_name -> stuko.api.v1.ingestion.ImportError
	0, // 1: stuko.api.v1.ingestion.IngestionService.TriggerDataImport:input_type -> stuko.api.v1.ingestion.TriggerDataImportRequest
	1, // 2: stuko.api.v1.ingestion.IngestionService.TriggerDataImport:output_type -> stuko.api.v1.ingestion.TriggerDataImportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_ingestion_proto_init() }
func file_api_proto_v1_ingestion_proto_init() {
	if File_api_proto_v1_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_ingestion_proto_rawDesc), len(file_api_proto_v1_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_ingestion_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_ingestion_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_ingestion_proto_msgTypes,
	}.Build()
	File_api_proto_v1_ingestion_proto = out.File
	file_api_proto_v1_ingestion_proto_goTypes = nil
	file_api_proto_v1_ingestion_proto_depIdxs = nil
}
