// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/dashboard.proto

package dashboardpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardStatsRequest) Reset() {
	*x = GetDashboardStatsRequest{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsRequest) ProtoMessage() {}

func (x *GetDashboardStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

type GetDashboardStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalBottles    int32                  `protobuf:"varint,1,opt,name=total_bottles,json=totalBottles,proto3" json:"total_bottles,omitempty"`
	TotalValue      float32                `protobuf:"fixed32,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	CategoriesCount int32                  `protobuf:"varint,3,opt,name=categories_count,json=categoriesCount,proto3" json:"categories_count,omitempty"`
	PendingAlerts   int32                  `protobuf:"varint,4,opt,name=pending_alerts,json=pendingAlerts,proto3" json:"pending_alerts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDashboardStatsResponse) Reset() {
	*x = GetDashboardStatsResponse{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardStatsResponse) ProtoMessage() {}

func (x *GetDashboardStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *GetDashboardStatsResponse) GetTotalBottles() int32 {
	if x != nil {
		return x.TotalBottles
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetTotalValue() float32 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetCategoriesCount() int32 {
	if x != nil {
		return x.CategoriesCount
	}
	return 0
}

func (x *GetDashboardStatsResponse) GetPendingAlerts() int32 {
	if x != nil {
		return x.PendingAlerts
	}
	return 0
}

type GetHighValueHoldingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighValueHoldingsRequest) Reset() {
	*x = GetHighValueHoldingsRequest{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighValueHoldingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighValueHoldingsRequest) ProtoMessage() {}

func (x *GetHighValueHoldingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighValueHoldingsRequest.ProtoReflect.Descriptor instead.
func (*GetHighValueHoldingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

type GetHighValueHoldingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*HoldingItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHighValueHoldingsResponse) Reset() {
	*x = GetHighValueHoldingsResponse{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHighValueHoldingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHighValueHoldingsResponse) ProtoMessage() {}

func (x *GetHighValueHoldingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHighValueHoldingsResponse.ProtoReflect.Descriptor instead.
func (*GetHighValueHoldingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *GetHighValueHoldingsResponse) GetItems() []*HoldingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type HoldingItem struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category              string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Value                 float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	PercentageOfPortfolio float32                `protobuf:"fixed32,4,opt,name=percentage_of_portfolio,json=percentageOfPortfolio,proto3" json:"percentage_of_portfolio,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HoldingItem) Reset() {
	*x = HoldingItem{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldingItem) ProtoMessage() {}

func (x *HoldingItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldingItem.ProtoReflect.Descriptor instead.
func (*HoldingItem) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *HoldingItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HoldingItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *HoldingItem) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *HoldingItem) GetPercentageOfPortfolio() float32 {
	if x != nil {
		return x.PercentageOfPortfolio
	}
	return 0
}

type GetMarketExposureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketExposureRequest) Reset() {
	*x = GetMarketExposureRequest{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketExposureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketExposureRequest) ProtoMessage() {}

func (x *GetMarketExposureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketExposureRequest.ProtoReflect.Descriptor instead.
func (*GetMarketExposureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

type GetMarketExposureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*ExposureCategory    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketExposureResponse) Reset() {
	*x = GetMarketExposureResponse{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketExposureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketExposureResponse) ProtoMessage() {}

func (x *GetMarketExposureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketExposureResponse.ProtoReflect.Descriptor instead.
func (*GetMarketExposureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetMarketExposureResponse) GetCategories() []*ExposureCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ExposureCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryName  string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExposureCategory) Reset() {
	*x = ExposureCategory{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExposureCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExposureCategory) ProtoMessage() {}

func (x *ExposureCategory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExposureCategory.ProtoReflect.Descriptor instead.
func (*ExposureCategory) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *ExposureCategory) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ExposureCategory) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ExposureCategory) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type GetForecastingFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastingFeedRequest) Reset() {
	*x = GetForecastingFeedRequest{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastingFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastingFeedRequest) ProtoMessage() {}

func (x *GetForecastingFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastingFeedRequest.ProtoReflect.Descriptor instead.
func (*GetForecastingFeedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{8}
}

type GetForecastingFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*ForecastingAlert    `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastingFeedResponse) Reset() {
	*x = GetForecastingFeedResponse{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastingFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastingFeedResponse) ProtoMessage() {}

func (x *GetForecastingFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastingFeedResponse.ProtoReflect.Descriptor instead.
func (*GetForecastingFeedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *GetForecastingFeedResponse) GetAlerts() []*ForecastingAlert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type ForecastingAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // "HIGH", "MEDIUM", "LOW"
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RelatedItemId string                 `protobuf:"bytes,5,opt,name=related_item_id,json=relatedItemId,proto3" json:"related_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastingAlert) Reset() {
	*x = ForecastingAlert{}
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastingAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastingAlert) ProtoMessage() {}

func (x *ForecastingAlert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastingAlert.ProtoReflect.Descriptor instead.
func (*ForecastingAlert) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *ForecastingAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForecastingAlert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForecastingAlert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ForecastingAlert) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ForecastingAlert) GetRelatedItemId() string {
	if x != nil {
		return x.RelatedItemId
	}
	return ""
}

var File_api_proto_v1_dashboard_proto protoreflect.FileDescriptor

const file_api_proto_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/dashboard.proto\x12\x16stuko.api.v1.dashboard\x1a\x1cgoogle/api/annotations.proto\"\x1a\n" +
	"\x18GetDashboardStatsRequest\"\xb3\x01\n" +
	"\x19GetDashboardStatsResponse\x12#\n" +
	"\rtotal_bottles\x18\x01 \x01(\x05R\ftotalBottles\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x02R\n" +
	"totalValue\x12)\n" +
	"\x10categories_count\x18\x03 \x01(\x05R\x0fcategoriesCount\x12%\n" +
	"\x0epending_alerts\x18\x04 \x01(\x05R\rpendingAlerts\"\x1d\n" +
	"\x1bGetHighValueHoldingsRequest\"Y\n" +
	"\x1cGetHighValueHoldingsResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.stuko.api.v1.dashboard.HoldingItemR\x05items\"\x8b\x01\n" +
	"\vHoldingItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\x126\n" +
	"\x17percentage_of_portfolio\x18\x04 \x01(\x02R\x15percentageOfPortfolio\"\x1a\n" +
	"\x18GetMarketExposureRequest\"e\n" +
	"\x19GetMarketExposureResponse\x12H\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2(.stuko.api.v1.dashboard.ExposureCategoryR\n" +
	"categories\"m\n" +
	"\x10ExposureCategory\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"\x1b\n" +
	"\x19GetForecastingFeedRequest\"^\n" +
	"\x1aGetForecastingFeedResponse\x12@\n" +
	"\x06alerts\x18\x01 \x03(\v2(.stuko.api.v1.dashboard.ForecastingAlertR\x06alerts\"\x9f\x01\n" +
	"\x10ForecastingAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12&\n" +
	"\x0frelated_item_id\x18\x05 \x01(\tR\rrelatedItemId2\xaa\x05\n" +
	"\x10DashboardService\x12\x95\x01\n" +
	"\x11GetDashboardStats\x120.stuko.api.v1.dashboard.GetDashboardStatsRequest\x1a1.stuko.api.v1.dashboard.GetDashboardStatsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/dashboard/stats\x12\xaf\x01\n" +
	"\x14GetHighValueHoldings\x123.stuko.api.v1.dashboard.GetHighValueHoldingsRequest\x1a4.stuko.api.v1.dashboard.GetHighValueHoldingsResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/dashboard/high-value-holdings\x12\xa2\x01\n" +
	"\x11GetMarketExposure\x120.stuko.api.v1.dashboard.GetMarketExposureRequest\x1a1.stuko.api.v1.dashboard.GetMarketExposureResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/dashboard/market-exposure\x12\xa6\x01\n" +
	"\x12GetForecastingFeed\x121.stuko.api.v1.dashboard.GetForecastingFeedRequest\x1a2.stuko.api.v1.dashboard.GetForecastingFeedResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/dashboard/forecasting-feedBIZGgithub.com/vinosPASI/vinos/backend/api/proto/v1/dashboardpb;dashboardpbb\x06proto3"

var (
	file_api_proto_v1_dashboard_proto_rawDescOnce sync.Once
	file_api_proto_v1_dashboard_proto_rawDescData []byte
)

func file_api_proto_v1_dashboard_proto_rawDescGZIP() []byte {
	file_api_proto_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_dashboard_proto_rawDesc), len(file_api_proto_v1_dashboard_proto_rawDesc)))
	})
	return file_api_proto_v1_dashboard_proto_rawDescData
}

var file_api_proto_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_v1_dashboard_proto_goTypes = []any{
	(*GetDashboardStatsRequest)(nil),     // 0: stuko.api.v1.dashboard.GetDashboardStatsRequest
	(*GetDashboardStatsResponse)(nil),    // 1: stuko.api.v1.dashboard.GetDashboardStatsResponse
	(*GetHighValueHoldingsRequest)(nil),  // 2: stuko.api.v1.dashboard.GetHighValueHoldingsRequest
	(*GetHighValueHoldingsResponse)(nil), // 3: stuko.api.v1.dashboard.GetHighValueHoldingsResponse
	(*HoldingItem)(nil),                  // 4: stuko.api.v1.dashboard.HoldingItem
	(*GetMarketExposureRequest)(nil),     // 5: stuko.api.v1.dashboard.GetMarketExposureRequest
	(*GetMarketExposureResponse)(nil),    // 6: stuko.api.v1.dashboard.GetMarketExposureResponse
	(*ExposureCategory)(nil),             // 7: stuko.api.v1.dashboard.ExposureCategory
	(*GetForecastingFeedRequest)(nil),    // 8: stuko.api.v1.dashboard.GetForecastingFeedRequest
	(*GetForecastingFeedResponse)(nil),   // 9: stuko.api.v1.dashboard.GetForecastingFeedResponse
	(*ForecastingAlert)(nil),             // 10: stuko.api.v1.dashboard.ForecastingAlert
}
var file_api_proto_v1_dashboard_proto_depIdxs = []int32{
	4,  // 0: stuko.api.v1.dashboard.GetHighValueHoldingsResponse.items:type_name -> stuko.api.v1.dashboard.HoldingItem
	7,  // 1: stuko.api.v1.dashboard.GetMarketExposureResponse.categories:type_name -> stuko.api.v1.dashboard.ExposureCategory
	10, // 2: stuko.api.v1.dashboard.GetForecastingFeedResponse.alerts:type_name -> stuko.api.v1.dashboard.ForecastingAlert
	0,  // 3: stuko.api.v1.dashboard.DashboardService.GetDashboardStats:input_type -> stuko.api.v1.dashboard.GetDashboardStatsRequest
	2,  // 4: stuko.api.v1.dashboard.DashboardService.GetHighValueHoldings:input_type -> stuko.api.v1.dashboard.GetHighValueHoldingsRequest
	5,  // 5: stuko.api.v1.dashboard.DashboardService.GetMarketExposure:input_type -> stuko.api.v1.dashboard.GetMarketExposureRequest
	8,  // 6: stuko.api.v1.dashboard.DashboardService.GetForecastingFeed:input_type -> stuko.api.v1.dashboard.GetForecastingFeedRequest
	1,  // 7: stuko.api.v1.dashboard.DashboardService.GetDashboardStats:output_type -> stuko.api.v1.dashboard.GetDashboardStatsResponse
	3,  // 8: stuko.api.v1.dashboard.DashboardService.GetHighValueHoldings:output_type -> stuko.api.v1.dashboard.GetHighValueHoldingsResponse
	6,  // 9: stuko.api.v1.dashboard.DashboardService.GetMarketExposure:output_type -> stuko.api.v1.dashboard.GetMarketExposureResponse
	9,  // 10: stuko.api.v1.dashboard.DashboardService.GetForecastingFeed:output_type -> stuko.api.v1.dashboard.GetForecastingFeedResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_dashboard_proto_init() }
func file_api_proto_v1_dashboard_proto_init() {
	if File_api_proto_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_dashboard_proto_rawDesc), len(file_api_proto_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_dashboard_proto_msgTypes,
	}.Build()
	File_api_proto_v1_dashboard_proto = out.File
	file_api_proto_v1_dashboard_proto_goTypes = nil
	file_api_proto_v1_dashboard_proto_depIdxs = nil
}
