// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/proto/v1/dashboard.proto

package dashboardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetDashboardStats_FullMethodName    = "/stuko.api.v1.dashboard.DashboardService/GetDashboardStats"
	DashboardService_GetHighValueHoldings_FullMethodName = "/stuko.api.v1.dashboard.DashboardService/GetHighValueHoldings"
	DashboardService_GetMarketExposure_FullMethodName    = "/stuko.api.v1.dashboard.DashboardService/GetMarketExposure"
	DashboardService_GetForecastingFeed_FullMethodName   = "/stuko.api.v1.dashboard.DashboardService/GetForecastingFeed"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio Orquestador para Analítica y Predicciones
type DashboardServiceClient interface {
	GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*GetDashboardStatsResponse, error)
	GetHighValueHoldings(ctx context.Context, in *GetHighValueHoldingsRequest, opts ...grpc.CallOption) (*GetHighValueHoldingsResponse, error)
	GetMarketExposure(ctx context.Context, in *GetMarketExposureRequest, opts ...grpc.CallOption) (*GetMarketExposureResponse, error)
	GetForecastingFeed(ctx context.Context, in *GetForecastingFeedRequest, opts ...grpc.CallOption) (*GetForecastingFeedResponse, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetDashboardStats(ctx context.Context, in *GetDashboardStatsRequest, opts ...grpc.CallOption) (*GetDashboardStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardStatsResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetHighValueHoldings(ctx context.Context, in *GetHighValueHoldingsRequest, opts ...grpc.CallOption) (*GetHighValueHoldingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHighValueHoldingsResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetHighValueHoldings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetMarketExposure(ctx context.Context, in *GetMarketExposureRequest, opts ...grpc.CallOption) (*GetMarketExposureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketExposureResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetMarketExposure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetForecastingFeed(ctx context.Context, in *GetForecastingFeedRequest, opts ...grpc.CallOption) (*GetForecastingFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetForecastingFeedResponse)
	err := c.cc.Invoke(ctx, DashboardService_GetForecastingFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
//
// Servicio Orquestador para Analítica y Predicciones
type DashboardServiceServer interface {
	GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*GetDashboardStatsResponse, error)
	GetHighValueHoldings(context.Context, *GetHighValueHoldingsRequest) (*GetHighValueHoldingsResponse, error)
	GetMarketExposure(context.Context, *GetMarketExposureRequest) (*GetMarketExposureResponse, error)
	GetForecastingFeed(context.Context, *GetForecastingFeedRequest) (*GetForecastingFeedResponse, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetDashboardStats(context.Context, *GetDashboardStatsRequest) (*GetDashboardStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardStats not implemented")
}
func (UnimplementedDashboardServiceServer) GetHighValueHoldings(context.Context, *GetHighValueHoldingsRequest) (*GetHighValueHoldingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHighValueHoldings not implemented")
}
func (UnimplementedDashboardServiceServer) GetMarketExposure(context.Context, *GetMarketExposureRequest) (*GetMarketExposureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketExposure not implemented")
}
func (UnimplementedDashboardServiceServer) GetForecastingFeed(context.Context, *GetForecastingFeedRequest) (*GetForecastingFeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForecastingFeed not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call panics, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetDashboardStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardStats(ctx, req.(*GetDashboardStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetHighValueHoldings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHighValueHoldingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetHighValueHoldings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetHighValueHoldings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetHighValueHoldings(ctx, req.(*GetHighValueHoldingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetMarketExposure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketExposureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetMarketExposure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetMarketExposure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetMarketExposure(ctx, req.(*GetMarketExposureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetForecastingFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForecastingFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetForecastingFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetForecastingFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetForecastingFeed(ctx, req.(*GetForecastingFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stuko.api.v1.dashboard.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardStats",
			Handler:    _DashboardService_GetDashboardStats_Handler,
		},
		{
			MethodName: "GetHighValueHoldings",
			Handler:    _DashboardService_GetHighValueHoldings_Handler,
		},
		{
			MethodName: "GetMarketExposure",
			Handler:    _DashboardService_GetMarketExposure_Handler,
		},
		{
			MethodName: "GetForecastingFeed",
			Handler:    _DashboardService_GetForecastingFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/dashboard.proto",
}
