// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/proto/v1/production.proto

package productionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductionService_CreateBottlingOrder_FullMethodName = "/stuko.api.v1.production.ProductionService/CreateBottlingOrder"
)

// ProductionServiceClient is the client API for ProductionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Maneja el proceso de embotellado, cruce de inventario de vino a granel e insumos secos y alertas de IA
type ProductionServiceClient interface {
	CreateBottlingOrder(ctx context.Context, in *CreateBottlingOrderRequest, opts ...grpc.CallOption) (*CreateBottlingOrderResponse, error)
}

type productionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductionServiceClient(cc grpc.ClientConnInterface) ProductionServiceClient {
	return &productionServiceClient{cc}
}

func (c *productionServiceClient) CreateBottlingOrder(ctx context.Context, in *CreateBottlingOrderRequest, opts ...grpc.CallOption) (*CreateBottlingOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBottlingOrderResponse)
	err := c.cc.Invoke(ctx, ProductionService_CreateBottlingOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductionServiceServer is the server API for ProductionService service.
// All implementations must embed UnimplementedProductionServiceServer
// for forward compatibility.
//
// Maneja el proceso de embotellado, cruce de inventario de vino a granel e insumos secos y alertas de IA
type ProductionServiceServer interface {
	CreateBottlingOrder(context.Context, *CreateBottlingOrderRequest) (*CreateBottlingOrderResponse, error)
	mustEmbedUnimplementedProductionServiceServer()
}

// UnimplementedProductionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductionServiceServer struct{}

func (UnimplementedProductionServiceServer) CreateBottlingOrder(context.Context, *CreateBottlingOrderRequest) (*CreateBottlingOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBottlingOrder not implemented")
}
func (UnimplementedProductionServiceServer) mustEmbedUnimplementedProductionServiceServer() {}
func (UnimplementedProductionServiceServer) testEmbeddedByValue()                           {}

// UnsafeProductionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductionServiceServer will
// result in compilation errors.
type UnsafeProductionServiceServer interface {
	mustEmbedUnimplementedProductionServiceServer()
}

func RegisterProductionServiceServer(s grpc.ServiceRegistrar, srv ProductionServiceServer) {
	// If the following call panics, it indicates UnimplementedProductionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductionService_ServiceDesc, srv)
}

func _ProductionService_CreateBottlingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBottlingOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductionServiceServer).CreateBottlingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductionService_CreateBottlingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductionServiceServer).CreateBottlingOrder(ctx, req.(*CreateBottlingOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductionService_ServiceDesc is the grpc.ServiceDesc for ProductionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stuko.api.v1.production.ProductionService",
	HandlerType: (*ProductionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBottlingOrder",
			Handler:    _ProductionService_CreateBottlingOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/production.proto",
}
