// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/production.proto

package productionpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBottlingOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WineId         string                 `protobuf:"bytes,1,opt,name=wine_id,json=wineId,proto3" json:"wine_id,omitempty"`
	TargetQuantity int32                  `protobuf:"varint,2,opt,name=target_quantity,json=targetQuantity,proto3" json:"target_quantity,omitempty"`
	UnitType       string                 `protobuf:"bytes,3,opt,name=unit_type,json=unitType,proto3" json:"unit_type,omitempty"`
	PlannedDate    int64                  `protobuf:"varint,4,opt,name=planned_date,json=plannedDate,proto3" json:"planned_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBottlingOrderRequest) Reset() {
	*x = CreateBottlingOrderRequest{}
	mi := &file_api_proto_v1_production_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBottlingOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBottlingOrderRequest) ProtoMessage() {}

func (x *CreateBottlingOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_production_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBottlingOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateBottlingOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_production_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBottlingOrderRequest) GetWineId() string {
	if x != nil {
		return x.WineId
	}
	return ""
}

func (x *CreateBottlingOrderRequest) GetTargetQuantity() int32 {
	if x != nil {
		return x.TargetQuantity
	}
	return 0
}

func (x *CreateBottlingOrderRequest) GetUnitType() string {
	if x != nil {
		return x.UnitType
	}
	return ""
}

func (x *CreateBottlingOrderRequest) GetPlannedDate() int64 {
	if x != nil {
		return x.PlannedDate
	}
	return 0
}

type CreateBottlingOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MaterialBreakdown []*MaterialDeduction   `protobuf:"bytes,2,rep,name=material_breakdown,json=materialBreakdown,proto3" json:"material_breakdown,omitempty"`
	StockAlert        *PredictiveStockAlert  `protobuf:"bytes,3,opt,name=stock_alert,json=stockAlert,proto3" json:"stock_alert,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBottlingOrderResponse) Reset() {
	*x = CreateBottlingOrderResponse{}
	mi := &file_api_proto_v1_production_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBottlingOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBottlingOrderResponse) ProtoMessage() {}

func (x *CreateBottlingOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_production_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBottlingOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateBottlingOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_production_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBottlingOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateBottlingOrderResponse) GetMaterialBreakdown() []*MaterialDeduction {
	if x != nil {
		return x.MaterialBreakdown
	}
	return nil
}

func (x *CreateBottlingOrderResponse) GetStockAlert() *PredictiveStockAlert {
	if x != nil {
		return x.StockAlert
	}
	return nil
}

type MaterialDeduction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaterialId       string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	MaterialName     string                 `protobuf:"bytes,2,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	QuantityToDeduct float32                `protobuf:"fixed32,3,opt,name=quantity_to_deduct,json=quantityToDeduct,proto3" json:"quantity_to_deduct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MaterialDeduction) Reset() {
	*x = MaterialDeduction{}
	mi := &file_api_proto_v1_production_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialDeduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialDeduction) ProtoMessage() {}

func (x *MaterialDeduction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_production_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialDeduction.ProtoReflect.Descriptor instead.
func (*MaterialDeduction) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_production_proto_rawDescGZIP(), []int{2}
}

func (x *MaterialDeduction) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *MaterialDeduction) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *MaterialDeduction) GetQuantityToDeduct() float32 {
	if x != nil {
		return x.QuantityToDeduct
	}
	return 0
}

type PredictiveStockAlert struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StockoutProbability float32                `protobuf:"fixed32,1,opt,name=stockout_probability,json=stockoutProbability,proto3" json:"stockout_probability,omitempty"`
	DiagnosticMessage   string                 `protobuf:"bytes,2,opt,name=diagnostic_message,json=diagnosticMessage,proto3" json:"diagnostic_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PredictiveStockAlert) Reset() {
	*x = PredictiveStockAlert{}
	mi := &file_api_proto_v1_production_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictiveStockAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictiveStockAlert) ProtoMessage() {}

func (x *PredictiveStockAlert) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_production_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictiveStockAlert.ProtoReflect.Descriptor instead.
func (*PredictiveStockAlert) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_production_proto_rawDescGZIP(), []int{3}
}

func (x *PredictiveStockAlert) GetStockoutProbability() float32 {
	if x != nil {
		return x.StockoutProbability
	}
	return 0
}

func (x *PredictiveStockAlert) GetDiagnosticMessage() string {
	if x != nil {
		return x.DiagnosticMessage
	}
	return ""
}

var File_api_proto_v1_production_proto protoreflect.FileDescriptor

const file_api_proto_v1_production_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/v1/production.proto\x12\x17stuko.api.v1.production\x1a\x1cgoogle/api/annotations.proto\"\x9e\x01\n" +
	"\x1aCreateBottlingOrderRequest\x12\x17\n" +
	"\awine_id\x18\x01 \x01(\tR\x06wineId\x12'\n" +
	"\x0ftarget_quantity\x18\x02 \x01(\x05R\x0etargetQuantity\x12\x1b\n" +
	"\tunit_type\x18\x03 \x01(\tR\bunitType\x12!\n" +
	"\fplanned_date\x18\x04 \x01(\x03R\vplannedDate\"\xe0\x01\n" +
	"\x1bCreateBottlingOrderResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12Y\n" +
	"\x12material_breakdown\x18\x02 \x03(\v2*.stuko.api.v1.production.MaterialDeductionR\x11materialBreakdown\x12N\n" +
	"\vstock_alert\x18\x03 \x01(\v2-.stuko.api.v1.production.PredictiveStockAlertR\n" +
	"stockAlert\"\x87\x01\n" +
	"\x11MaterialDeduction\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12#\n" +
	"\rmaterial_name\x18\x02 \x01(\tR\fmaterialName\x12,\n" +
	"\x12quantity_to_deduct\x18\x03 \x01(\x02R\x10quantityToDeduct\"x\n" +
	"\x14PredictiveStockAlert\x121\n" +
	"\x14stockout_probability\x18\x01 \x01(\x02R\x13stockoutProbability\x12-\n" +
	"\x12diagnostic_message\x18\x02 \x01(\tR\x11diagnosticMessage2\xc0\x01\n" +
	"\x11ProductionService\x12\xaa\x01\n" +
	"\x13CreateBottlingOrder\x123.stuko.api.v1.production.CreateBottlingOrderRequest\x1a4.stuko.api.v1.production.CreateBottlingOrderResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/production/bottling-orderBKZIgithub.com/vinosPASI/vinos/backend/api/proto/v1/productionpb;productionpbb\x06proto3"

var (
	file_api_proto_v1_production_proto_rawDescOnce sync.Once
	file_api_proto_v1_production_proto_rawDescData []byte
)

func file_api_proto_v1_production_proto_rawDescGZIP() []byte {
	file_api_proto_v1_production_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_production_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_production_proto_rawDesc), len(file_api_proto_v1_production_proto_rawDesc)))
	})
	return file_api_proto_v1_production_proto_rawDescData
}

var file_api_proto_v1_production_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_production_proto_goTypes = []any{
	(*CreateBottlingOrderRequest)(nil),  // 0: stuko.api.v1.production.CreateBottlingOrderRequest
	(*CreateBottlingOrderResponse)(nil), // 1: stuko.api.v1.production.CreateBottlingOrderResponse
	(*MaterialDeduction)(nil),           // 2: stuko.api.v1.production.MaterialDeduction
	(*PredictiveStockAlert)(nil),        // 3: stuko.api.v1.production.PredictiveStockAlert
}
var file_api_proto_v1_production_proto_depIdxs = []int32{
	2, // 0: stuko.api.v1.production.CreateBottlingOrderResponse.material_breakdown:type_name -> stuko.api.v1.production.MaterialDeduction
	3, // 1: stuko.api.v1.production.CreateBottlingOrderResponse.stock_alert:type_name -> stuko.api.v1.production.PredictiveStockAlert
	0, // 2: stuko.api.v1.production.ProductionService.CreateBottlingOrder:input_type -> stuko.api.v1.production.CreateBottlingOrderRequest
	1, // 3: stuko.api.v1.production.ProductionService.CreateBottlingOrder:output_type -> stuko.api.v1.production.CreateBottlingOrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_production_proto_init() }
func file_api_proto_v1_production_proto_init() {
	if File_api_proto_v1_production_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_production_proto_rawDesc), len(file_api_proto_v1_production_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_production_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_production_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_production_proto_msgTypes,
	}.Build()
	File_api_proto_v1_production_proto = out.File
	file_api_proto_v1_production_proto_goTypes = nil
	file_api_proto_v1_production_proto_depIdxs = nil
}
