// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/v1/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{0}
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	RealStock     int32                  `protobuf:"varint,4,opt,name=real_stock,json=realStock,proto3" json:"real_stock,omitempty"`
	NetStock      int32                  `protobuf:"varint,5,opt,name=net_stock,json=netStock,proto3" json:"net_stock,omitempty"`
	Warehouse     string                 `protobuf:"bytes,6,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryItem) GetRealStock() int32 {
	if x != nil {
		return x.RealStock
	}
	return 0
}

func (x *InventoryItem) GetNetStock() int32 {
	if x != nil {
		return x.NetStock
	}
	return 0
}

func (x *InventoryItem) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetItemDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemDetailRequest) Reset() {
	*x = GetItemDetailRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDetailRequest) ProtoMessage() {}

func (x *GetItemDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDetailRequest.ProtoReflect.Descriptor instead.
func (*GetItemDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Movement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movement) Reset() {
	*x = Movement{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *Movement) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Movement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Movement) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Movement) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type StockPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPoint) Reset() {
	*x = StockPoint{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPoint) ProtoMessage() {}

func (x *StockPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPoint.ProtoReflect.Descriptor instead.
func (*StockPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *StockPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StockPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetItemDetailResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RunwayDays         int32                  `protobuf:"varint,3,opt,name=runway_days,json=runwayDays,proto3" json:"runway_days,omitempty"`
	StockoutDate       string                 `protobuf:"bytes,4,opt,name=stockout_date,json=stockoutDate,proto3" json:"stockout_date,omitempty"`
	ConsumptionHistory []*StockPoint          `protobuf:"bytes,5,rep,name=consumption_history,json=consumptionHistory,proto3" json:"consumption_history,omitempty"`
	MovementHistory    []*Movement            `protobuf:"bytes,6,rep,name=movement_history,json=movementHistory,proto3" json:"movement_history,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetItemDetailResponse) Reset() {
	*x = GetItemDetailResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDetailResponse) ProtoMessage() {}

func (x *GetItemDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDetailResponse.ProtoReflect.Descriptor instead.
func (*GetItemDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemDetailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetItemDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetItemDetailResponse) GetRunwayDays() int32 {
	if x != nil {
		return x.RunwayDays
	}
	return 0
}

func (x *GetItemDetailResponse) GetStockoutDate() string {
	if x != nil {
		return x.StockoutDate
	}
	return ""
}

func (x *GetItemDetailResponse) GetConsumptionHistory() []*StockPoint {
	if x != nil {
		return x.ConsumptionHistory
	}
	return nil
}

func (x *GetItemDetailResponse) GetMovementHistory() []*Movement {
	if x != nil {
		return x.MovementHistory
	}
	return nil
}

var File_api_proto_v1_inventory_proto protoreflect.FileDescriptor

const file_api_proto_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/inventory.proto\x12\x16stuko.api.v1.inventory\"\x12\n" +
	"\x10ListItemsRequest\"\x9f\x01\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x1d\n" +
	"\n" +
	"real_stock\x18\x04 \x01(\x05R\trealStock\x12\x1b\n" +
	"\tnet_stock\x18\x05 \x01(\x05R\bnetStock\x12\x1c\n" +
	"\twarehouse\x18\x06 \x01(\tR\twarehouse\"P\n" +
	"\x11ListItemsResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.stuko.api.v1.inventory.InventoryItemR\x05items\"&\n" +
	"\x14GetItemDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\bMovement\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"(\n" +
	"\n" +
	"StockPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xa3\x02\n" +
	"\x15GetItemDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vrunway_days\x18\x03 \x01(\x05R\n" +
	"runwayDays\x12#\n" +
	"\rstockout_date\x18\x04 \x01(\tR\fstockoutDate\x12S\n" +
	"\x13consumption_history\x18\x05 \x03(\v2\".stuko.api.v1.inventory.StockPointR\x12consumptionHistory\x12K\n" +
	"\x10movement_history\x18\x06 \x03(\v2 .stuko.api.v1.inventory.MovementR\x0fmovementHistory2\xe2\x01\n" +
	"\x10InventoryService\x12`\n" +
	"\tListItems\x12(.stuko.api.v1.inventory.ListItemsRequest\x1a).stuko.api.v1.inventory.ListItemsResponse\x12l\n" +
	"\rGetItemDetail\x12,.stuko.api.v1.inventory.GetItemDetailRequest\x1a-.stuko.api.v1.inventory.GetItemDetailResponseB=Z;github.com/vinosPASI/vinos/backend/api/proto/v1/inventorypbb\x06proto3"

var (
	file_api_proto_v1_inventory_proto_rawDescOnce sync.Once
	file_api_proto_v1_inventory_proto_rawDescData []byte
)

func file_api_proto_v1_inventory_proto_rawDescGZIP() []byte {
	file_api_proto_v1_inventory_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_inventory_proto_rawDesc), len(file_api_proto_v1_inventory_proto_rawDesc)))
	})
	return file_api_proto_v1_inventory_proto_rawDescData
}

var file_api_proto_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_v1_inventory_proto_goTypes = []any{
	(*ListItemsRequest)(nil),      // 0: stuko.api.v1.inventory.ListItemsRequest
	(*InventoryItem)(nil),         // 1: stuko.api.v1.inventory.InventoryItem
	(*ListItemsResponse)(nil),     // 2: stuko.api.v1.inventory.ListItemsResponse
	(*GetItemDetailRequest)(nil),  // 3: stuko.api.v1.inventory.GetItemDetailRequest
	(*Movement)(nil),              // 4: stuko.api.v1.inventory.Movement
	(*StockPoint)(nil),            // 5: stuko.api.v1.inventory.StockPoint
	(*GetItemDetailResponse)(nil), // 6: stuko.api.v1.inventory.GetItemDetailResponse
}
var file_api_proto_v1_inventory_proto_depIdxs = []int32{
	1, // 0: stuko.api.v1.inventory.ListItemsResponse.items:type_name -> stuko.api.v1.inventory.InventoryItem
	5, // 1: stuko.api.v1.inventory.GetItemDetailResponse.consumption_history:type_name -> stuko.api.v1.inventory.StockPoint
	4, // 2: stuko.api.v1.inventory.GetItemDetailResponse.movement_history:type_name -> stuko.api.v1.inventory.Movement
	0, // 3: stuko.api.v1.inventory.InventoryService.ListItems:input_type -> stuko.api.v1.inventory.ListItemsRequest
	3, // 4: stuko.api.v1.inventory.InventoryService.GetItemDetail:input_type -> stuko.api.v1.inventory.GetItemDetailRequest
	2, // 5: stuko.api.v1.inventory.InventoryService.ListItems:output_type -> stuko.api.v1.inventory.ListItemsResponse
	6, // 6: stuko.api.v1.inventory.InventoryService.GetItemDetail:output_type -> stuko.api.v1.inventory.GetItemDetailResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_inventory_proto_init() }
func file_api_proto_v1_inventory_proto_init() {
	if File_api_proto_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_inventory_proto_rawDesc), len(file_api_proto_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_inventory_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_inventory_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_inventory_proto_msgTypes,
	}.Build()
	File_api_proto_v1_inventory_proto = out.File
	file_api_proto_v1_inventory_proto_goTypes = nil
	file_api_proto_v1_inventory_proto_depIdxs = nil
}
