// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/inventory.proto

package inventorypb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListInventoryItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryItemsRequest) Reset() {
	*x = ListInventoryItemsRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryItemsRequest) ProtoMessage() {}

func (x *ListInventoryItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryItemsRequest.ProtoReflect.Descriptor instead.
func (*ListInventoryItemsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ListInventoryItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListInventoryItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInventoryItemsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListInventoryItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalItems    int32                  `protobuf:"varint,2,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInventoryItemsResponse) Reset() {
	*x = ListInventoryItemsResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInventoryItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInventoryItemsResponse) ProtoMessage() {}

func (x *ListInventoryItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInventoryItemsResponse.ProtoReflect.Descriptor instead.
func (*ListInventoryItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ListInventoryItemsResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListInventoryItemsResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *ListInventoryItemsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryItemRequest) Reset() {
	*x = GetInventoryItemRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryItemRequest) ProtoMessage() {}

func (x *GetInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	RealStock     int32                  `protobuf:"varint,7,opt,name=real_stock,json=realStock,proto3" json:"real_stock,omitempty"`
	NetStock      int32                  `protobuf:"varint,8,opt,name=net_stock,json=netStock,proto3" json:"net_stock,omitempty"`
	Warehouse     string                 `protobuf:"bytes,9,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *InventoryItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryItem) GetRealStock() int32 {
	if x != nil {
		return x.RealStock
	}
	return 0
}

func (x *InventoryItem) GetNetStock() int32 {
	if x != nil {
		return x.NetStock
	}
	return 0
}

func (x *InventoryItem) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

func (x *InventoryItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InventoryItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Movement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movement) Reset() {
	*x = Movement{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *Movement) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Movement) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Movement) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Movement) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type StockPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockPoint) Reset() {
	*x = StockPoint{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockPoint) ProtoMessage() {}

func (x *StockPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockPoint.ProtoReflect.Descriptor instead.
func (*StockPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *StockPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StockPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetInventoryItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Item  *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	// Detail fields for dashboard projections
	RunwayDays         int32         `protobuf:"varint,2,opt,name=runway_days,json=runwayDays,proto3" json:"runway_days,omitempty"`
	StockoutDate       string        `protobuf:"bytes,3,opt,name=stockout_date,json=stockoutDate,proto3" json:"stockout_date,omitempty"`
	ConsumptionHistory []*StockPoint `protobuf:"bytes,4,rep,name=consumption_history,json=consumptionHistory,proto3" json:"consumption_history,omitempty"`
	MovementHistory    []*Movement   `protobuf:"bytes,5,rep,name=movement_history,json=movementHistory,proto3" json:"movement_history,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInventoryItemResponse) Reset() {
	*x = GetInventoryItemResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryItemResponse) ProtoMessage() {}

func (x *GetInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetInventoryItemResponse) GetRunwayDays() int32 {
	if x != nil {
		return x.RunwayDays
	}
	return 0
}

func (x *GetInventoryItemResponse) GetStockoutDate() string {
	if x != nil {
		return x.StockoutDate
	}
	return ""
}

func (x *GetInventoryItemResponse) GetConsumptionHistory() []*StockPoint {
	if x != nil {
		return x.ConsumptionHistory
	}
	return nil
}

func (x *GetInventoryItemResponse) GetMovementHistory() []*Movement {
	if x != nil {
		return x.MovementHistory
	}
	return nil
}

type CreateInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Sku           string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Warehouse     string                 `protobuf:"bytes,6,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryItemRequest) Reset() {
	*x = CreateInventoryItemRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryItemRequest) ProtoMessage() {}

func (x *CreateInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*CreateInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInventoryItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInventoryItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateInventoryItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInventoryItemRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateInventoryItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateInventoryItemRequest) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

type CreateInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryItemResponse) Reset() {
	*x = CreateInventoryItemResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryItemResponse) ProtoMessage() {}

func (x *CreateInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*CreateInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Warehouse     string                 `protobuf:"bytes,7,opt,name=warehouse,proto3" json:"warehouse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryItemRequest) Reset() {
	*x = UpdateInventoryItemRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryItemRequest) ProtoMessage() {}

func (x *UpdateInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateInventoryItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInventoryItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateInventoryItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateInventoryItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateInventoryItemRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UpdateInventoryItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateInventoryItemRequest) GetWarehouse() string {
	if x != nil {
		return x.Warehouse
	}
	return ""
}

type UpdateInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *InventoryItem         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryItemResponse) Reset() {
	*x = UpdateInventoryItemResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryItemResponse) ProtoMessage() {}

func (x *UpdateInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateInventoryItemResponse) GetItem() *InventoryItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteInventoryItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryItemRequest) Reset() {
	*x = DeleteInventoryItemRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryItemRequest) ProtoMessage() {}

func (x *DeleteInventoryItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteInventoryItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteInventoryItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteInventoryItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryItemResponse) Reset() {
	*x = DeleteInventoryItemResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryItemResponse) ProtoMessage() {}

func (x *DeleteInventoryItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteInventoryItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteInventoryItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RecordMovementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	MovementType  string                 `protobuf:"bytes,2,opt,name=movement_type,json=movementType,proto3" json:"movement_type,omitempty"` // IN or OUT
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMovementRequest) Reset() {
	*x = RecordMovementRequest{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMovementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMovementRequest) ProtoMessage() {}

func (x *RecordMovementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMovementRequest.ProtoReflect.Descriptor instead.
func (*RecordMovementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *RecordMovementRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RecordMovementRequest) GetMovementType() string {
	if x != nil {
		return x.MovementType
	}
	return ""
}

func (x *RecordMovementRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RecordMovementRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecordMovementRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type RecordMovementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedItem   *InventoryItem         `protobuf:"bytes,2,opt,name=updated_item,json=updatedItem,proto3" json:"updated_item,omitempty"`
	MovementId    string                 `protobuf:"bytes,3,opt,name=movement_id,json=movementId,proto3" json:"movement_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMovementResponse) Reset() {
	*x = RecordMovementResponse{}
	mi := &file_api_proto_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMovementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMovementResponse) ProtoMessage() {}

func (x *RecordMovementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMovementResponse.ProtoReflect.Descriptor instead.
func (*RecordMovementResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *RecordMovementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordMovementResponse) GetUpdatedItem() *InventoryItem {
	if x != nil {
		return x.UpdatedItem
	}
	return nil
}

func (x *RecordMovementResponse) GetMovementId() string {
	if x != nil {
		return x.MovementId
	}
	return ""
}

var File_api_proto_v1_inventory_proto protoreflect.FileDescriptor

const file_api_proto_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/inventory.proto\x12\x16stuko.api.v1.inventory\x1a\x1cgoogle/api/annotations.proto\"]\n" +
	"\x19ListInventoryItemsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x9b\x01\n" +
	"\x1aListInventoryItemsResponse\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.stuko.api.v1.inventory.InventoryItemR\x05items\x12\x1f\n" +
	"\vtotal_items\x18\x02 \x01(\x05R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\")\n" +
	"\x17GetInventoryItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa1\x02\n" +
	"\rInventoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1d\n" +
	"\n" +
	"real_stock\x18\a \x01(\x05R\trealStock\x12\x1b\n" +
	"\tnet_stock\x18\b \x01(\x05R\bnetStock\x12\x1c\n" +
	"\twarehouse\x18\t \x01(\tR\twarehouse\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"l\n" +
	"\bMovement\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"(\n" +
	"\n" +
	"StockPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xbd\x02\n" +
	"\x18GetInventoryItemResponse\x129\n" +
	"\x04item\x18\x01 \x01(\v2%.stuko.api.v1.inventory.InventoryItemR\x04item\x12\x1f\n" +
	"\vrunway_days\x18\x02 \x01(\x05R\n" +
	"runwayDays\x12#\n" +
	"\rstockout_date\x18\x03 \x01(\tR\fstockoutDate\x12S\n" +
	"\x13consumption_history\x18\x04 \x03(\v2\".stuko.api.v1.inventory.StockPointR\x12consumptionHistory\x12K\n" +
	"\x10movement_history\x18\x05 \x03(\v2 .stuko.api.v1.inventory.MovementR\x0fmovementHistory\"\xa4\x01\n" +
	"\x1aCreateInventoryItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x1c\n" +
	"\twarehouse\x18\x06 \x01(\tR\twarehouse\"X\n" +
	"\x1bCreateInventoryItemResponse\x129\n" +
	"\x04item\x18\x01 \x01(\v2%.stuko.api.v1.inventory.InventoryItemR\x04item\"\xb4\x01\n" +
	"\x1aUpdateInventoryItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1c\n" +
	"\twarehouse\x18\a \x01(\tR\twarehouse\"X\n" +
	"\x1bUpdateInventoryItemResponse\x129\n" +
	"\x04item\x18\x01 \x01(\v2%.stuko.api.v1.inventory.InventoryItemR\x04item\",\n" +
	"\x1aDeleteInventoryItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x1bDeleteInventoryItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xac\x01\n" +
	"\x15RecordMovementRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12#\n" +
	"\rmovement_type\x18\x02 \x01(\tR\fmovementType\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"\x9d\x01\n" +
	"\x16RecordMovementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12H\n" +
	"\fupdated_item\x18\x02 \x01(\v2%.stuko.api.v1.inventory.InventoryItemR\vupdatedItem\x12\x1f\n" +
	"\vmovement_id\x18\x03 \x01(\tR\n" +
	"movementId2\xb0\a\n" +
	"\x10InventoryService\x12\x9a\x01\n" +
	"\x12ListInventoryItems\x121.stuko.api.v1.inventory.ListInventoryItemsRequest\x1a2.stuko.api.v1.inventory.ListInventoryItemsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/inventory/list\x12\x91\x01\n" +
	"\x10GetInventoryItem\x12/.stuko.api.v1.inventory.GetInventoryItemRequest\x1a0.stuko.api.v1.inventory.GetInventoryItemResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/inventory/{id}\x12\x98\x01\n" +
	"\x13CreateInventoryItem\x122.stuko.api.v1.inventory.CreateInventoryItemRequest\x1a3.stuko.api.v1.inventory.CreateInventoryItemResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/inventory\x12\x9d\x01\n" +
	"\x13UpdateInventoryItem\x122.stuko.api.v1.inventory.UpdateInventoryItemRequest\x1a3.stuko.api.v1.inventory.UpdateInventoryItemResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/inventory/{id}\x12\x9a\x01\n" +
	"\x13DeleteInventoryItem\x122.stuko.api.v1.inventory.DeleteInventoryItemRequest\x1a3.stuko.api.v1.inventory.DeleteInventoryItemResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/inventory/{id}\x12\x92\x01\n" +
	"\x0eRecordMovement\x12-.stuko.api.v1.inventory.RecordMovementRequest\x1a..stuko.api.v1.inventory.RecordMovementResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/inventory/movementBIZGgithub.com/vinosPASI/vinos/backend/api/proto/v1/inventorypb;inventorypbb\x06proto3"

var (
	file_api_proto_v1_inventory_proto_rawDescOnce sync.Once
	file_api_proto_v1_inventory_proto_rawDescData []byte
)

func file_api_proto_v1_inventory_proto_rawDescGZIP() []byte {
	file_api_proto_v1_inventory_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_inventory_proto_rawDesc), len(file_api_proto_v1_inventory_proto_rawDesc)))
	})
	return file_api_proto_v1_inventory_proto_rawDescData
}

var file_api_proto_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_v1_inventory_proto_goTypes = []any{
	(*ListInventoryItemsRequest)(nil),   // 0: stuko.api.v1.inventory.ListInventoryItemsRequest
	(*ListInventoryItemsResponse)(nil),  // 1: stuko.api.v1.inventory.ListInventoryItemsResponse
	(*GetInventoryItemRequest)(nil),     // 2: stuko.api.v1.inventory.GetInventoryItemRequest
	(*InventoryItem)(nil),               // 3: stuko.api.v1.inventory.InventoryItem
	(*Movement)(nil),                    // 4: stuko.api.v1.inventory.Movement
	(*StockPoint)(nil),                  // 5: stuko.api.v1.inventory.StockPoint
	(*GetInventoryItemResponse)(nil),    // 6: stuko.api.v1.inventory.GetInventoryItemResponse
	(*CreateInventoryItemRequest)(nil),  // 7: stuko.api.v1.inventory.CreateInventoryItemRequest
	(*CreateInventoryItemResponse)(nil), // 8: stuko.api.v1.inventory.CreateInventoryItemResponse
	(*UpdateInventoryItemRequest)(nil),  // 9: stuko.api.v1.inventory.UpdateInventoryItemRequest
	(*UpdateInventoryItemResponse)(nil), // 10: stuko.api.v1.inventory.UpdateInventoryItemResponse
	(*DeleteInventoryItemRequest)(nil),  // 11: stuko.api.v1.inventory.DeleteInventoryItemRequest
	(*DeleteInventoryItemResponse)(nil), // 12: stuko.api.v1.inventory.DeleteInventoryItemResponse
	(*RecordMovementRequest)(nil),       // 13: stuko.api.v1.inventory.RecordMovementRequest
	(*RecordMovementResponse)(nil),      // 14: stuko.api.v1.inventory.RecordMovementResponse
}
var file_api_proto_v1_inventory_proto_depIdxs = []int32{
	3,  // 0: stuko.api.v1.inventory.ListInventoryItemsResponse.items:type_name -> stuko.api.v1.inventory.InventoryItem
	3,  // 1: stuko.api.v1.inventory.GetInventoryItemResponse.item:type_name -> stuko.api.v1.inventory.InventoryItem
	5,  // 2: stuko.api.v1.inventory.GetInventoryItemResponse.consumption_history:type_name -> stuko.api.v1.inventory.StockPoint
	4,  // 3: stuko.api.v1.inventory.GetInventoryItemResponse.movement_history:type_name -> stuko.api.v1.inventory.Movement
	3,  // 4: stuko.api.v1.inventory.CreateInventoryItemResponse.item:type_name -> stuko.api.v1.inventory.InventoryItem
	3,  // 5: stuko.api.v1.inventory.UpdateInventoryItemResponse.item:type_name -> stuko.api.v1.inventory.InventoryItem
	3,  // 6: stuko.api.v1.inventory.RecordMovementResponse.updated_item:type_name -> stuko.api.v1.inventory.InventoryItem
	0,  // 7: stuko.api.v1.inventory.InventoryService.ListInventoryItems:input_type -> stuko.api.v1.inventory.ListInventoryItemsRequest
	2,  // 8: stuko.api.v1.inventory.InventoryService.GetInventoryItem:input_type -> stuko.api.v1.inventory.GetInventoryItemRequest
	7,  // 9: stuko.api.v1.inventory.InventoryService.CreateInventoryItem:input_type -> stuko.api.v1.inventory.CreateInventoryItemRequest
	9,  // 10: stuko.api.v1.inventory.InventoryService.UpdateInventoryItem:input_type -> stuko.api.v1.inventory.UpdateInventoryItemRequest
	11, // 11: stuko.api.v1.inventory.InventoryService.DeleteInventoryItem:input_type -> stuko.api.v1.inventory.DeleteInventoryItemRequest
	13, // 12: stuko.api.v1.inventory.InventoryService.RecordMovement:input_type -> stuko.api.v1.inventory.RecordMovementRequest
	1,  // 13: stuko.api.v1.inventory.InventoryService.ListInventoryItems:output_type -> stuko.api.v1.inventory.ListInventoryItemsResponse
	6,  // 14: stuko.api.v1.inventory.InventoryService.GetInventoryItem:output_type -> stuko.api.v1.inventory.GetInventoryItemResponse
	8,  // 15: stuko.api.v1.inventory.InventoryService.CreateInventoryItem:output_type -> stuko.api.v1.inventory.CreateInventoryItemResponse
	10, // 16: stuko.api.v1.inventory.InventoryService.UpdateInventoryItem:output_type -> stuko.api.v1.inventory.UpdateInventoryItemResponse
	12, // 17: stuko.api.v1.inventory.InventoryService.DeleteInventoryItem:output_type -> stuko.api.v1.inventory.DeleteInventoryItemResponse
	14, // 18: stuko.api.v1.inventory.InventoryService.RecordMovement:output_type -> stuko.api.v1.inventory.RecordMovementResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_inventory_proto_init() }
func file_api_proto_v1_inventory_proto_init() {
	if File_api_proto_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_inventory_proto_rawDesc), len(file_api_proto_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_inventory_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_inventory_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_inventory_proto_msgTypes,
	}.Build()
	File_api_proto_v1_inventory_proto = out.File
	file_api_proto_v1_inventory_proto_goTypes = nil
	file_api_proto_v1_inventory_proto_depIdxs = nil
}
