name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Lint and Test Go Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.4'
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Go Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build Go Binary
        run: go build -v ./cmd/server/...

      - name: Run Tests
        run: go test -v ./...