// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/vision.proto

package visionpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeWineLabelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageReference string                 `protobuf:"bytes,1,opt,name=image_reference,json=imageReference,proto3" json:"image_reference,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeWineLabelRequest) Reset() {
	*x = AnalyzeWineLabelRequest{}
	mi := &file_api_proto_v1_vision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeWineLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeWineLabelRequest) ProtoMessage() {}

func (x *AnalyzeWineLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_vision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeWineLabelRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeWineLabelRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_vision_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeWineLabelRequest) GetImageReference() string {
	if x != nil {
		return x.ImageReference
	}
	return ""
}

type AnalyzeWineLabelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawOcrText     string                 `protobuf:"bytes,1,opt,name=raw_ocr_text,json=rawOcrText,proto3" json:"raw_ocr_text,omitempty"`
	Classification *ImageClassification   `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	WineData       *StructuredWineData    `protobuf:"bytes,3,opt,name=wine_data,json=wineData,proto3" json:"wine_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeWineLabelResponse) Reset() {
	*x = AnalyzeWineLabelResponse{}
	mi := &file_api_proto_v1_vision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeWineLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeWineLabelResponse) ProtoMessage() {}

func (x *AnalyzeWineLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_vision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeWineLabelResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeWineLabelResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_vision_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeWineLabelResponse) GetRawOcrText() string {
	if x != nil {
		return x.RawOcrText
	}
	return ""
}

func (x *AnalyzeWineLabelResponse) GetClassification() *ImageClassification {
	if x != nil {
		return x.Classification
	}
	return nil
}

func (x *AnalyzeWineLabelResponse) GetWineData() *StructuredWineData {
	if x != nil {
		return x.WineData
	}
	return nil
}

type ImageClassification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ConfidenceLevel float32                `protobuf:"fixed32,2,opt,name=confidence_level,json=confidenceLevel,proto3" json:"confidence_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImageClassification) Reset() {
	*x = ImageClassification{}
	mi := &file_api_proto_v1_vision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageClassification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageClassification) ProtoMessage() {}

func (x *ImageClassification) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_vision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageClassification.ProtoReflect.Descriptor instead.
func (*ImageClassification) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_vision_proto_rawDescGZIP(), []int{2}
}

func (x *ImageClassification) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ImageClassification) GetConfidenceLevel() float32 {
	if x != nil {
		return x.ConfidenceLevel
	}
	return 0
}

type StructuredWineData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	CepaVariedad  string                 `protobuf:"bytes,2,opt,name=cepa_variedad,json=cepaVariedad,proto3" json:"cepa_variedad,omitempty"`
	VintageYear   int32                  `protobuf:"varint,3,opt,name=vintage_year,json=vintageYear,proto3" json:"vintage_year,omitempty"`
	VolumeContent string                 `protobuf:"bytes,4,opt,name=volume_content,json=volumeContent,proto3" json:"volume_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredWineData) Reset() {
	*x = StructuredWineData{}
	mi := &file_api_proto_v1_vision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredWineData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredWineData) ProtoMessage() {}

func (x *StructuredWineData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_vision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredWineData.ProtoReflect.Descriptor instead.
func (*StructuredWineData) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_vision_proto_rawDescGZIP(), []int{3}
}

func (x *StructuredWineData) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *StructuredWineData) GetCepaVariedad() string {
	if x != nil {
		return x.CepaVariedad
	}
	return ""
}

func (x *StructuredWineData) GetVintageYear() int32 {
	if x != nil {
		return x.VintageYear
	}
	return 0
}

func (x *StructuredWineData) GetVolumeContent() string {
	if x != nil {
		return x.VolumeContent
	}
	return ""
}

var File_api_proto_v1_vision_proto protoreflect.FileDescriptor

const file_api_proto_v1_vision_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/vision.proto\x12\x13stuko.api.v1.vision\x1a\x1cgoogle/api/annotations.proto\"B\n" +
	"\x17AnalyzeWineLabelRequest\x12'\n" +
	"\x0fimage_reference\x18\x01 \x01(\tR\x0eimageReference\"\xd4\x01\n" +
	"\x18AnalyzeWineLabelResponse\x12 \n" +
	"\fraw_ocr_text\x18\x01 \x01(\tR\n" +
	"rawOcrText\x12P\n" +
	"\x0eclassification\x18\x02 \x01(\v2(.stuko.api.v1.vision.ImageClassificationR\x0eclassification\x12D\n" +
	"\twine_data\x18\x03 \x01(\v2'.stuko.api.v1.vision.StructuredWineDataR\bwineData\"V\n" +
	"\x13ImageClassification\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12)\n" +
	"\x10confidence_level\x18\x02 \x01(\x02R\x0fconfidenceLevel\"\x99\x01\n" +
	"\x12StructuredWineData\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12#\n" +
	"\rcepa_variedad\x18\x02 \x01(\tR\fcepaVariedad\x12!\n" +
	"\fvintage_year\x18\x03 \x01(\x05R\vvintageYear\x12%\n" +
	"\x0evolume_content\x18\x04 \x01(\tR\rvolumeContent2\xa0\x01\n" +
	"\rVisionService\x12\x8e\x01\n" +
	"\x10AnalyzeWineLabel\x12,.stuko.api.v1.vision.AnalyzeWineLabelRequest\x1a-.stuko.api.v1.vision.AnalyzeWineLabelResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/vision/analyzeBCZAgithub.com/vinosPASI/vinos/backend/api/proto/v1/visionpb;visionpbb\x06proto3"

var (
	file_api_proto_v1_vision_proto_rawDescOnce sync.Once
	file_api_proto_v1_vision_proto_rawDescData []byte
)

func file_api_proto_v1_vision_proto_rawDescGZIP() []byte {
	file_api_proto_v1_vision_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_vision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_vision_proto_rawDesc), len(file_api_proto_v1_vision_proto_rawDesc)))
	})
	return file_api_proto_v1_vision_proto_rawDescData
}

var file_api_proto_v1_vision_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_vision_proto_goTypes = []any{
	(*AnalyzeWineLabelRequest)(nil),  // 0: stuko.api.v1.vision.AnalyzeWineLabelRequest
	(*AnalyzeWineLabelResponse)(nil), // 1: stuko.api.v1.vision.AnalyzeWineLabelResponse
	(*ImageClassification)(nil),      // 2: stuko.api.v1.vision.ImageClassification
	(*StructuredWineData)(nil),       // 3: stuko.api.v1.vision.StructuredWineData
}
var file_api_proto_v1_vision_proto_depIdxs = []int32{
	2, // 0: stuko.api.v1.vision.AnalyzeWineLabelResponse.classification:type_name -> stuko.api.v1.vision.ImageClassification
	3, // 1: stuko.api.v1.vision.AnalyzeWineLabelResponse.wine_data:type_name -> stuko.api.v1.vision.StructuredWineData
	0, // 2: stuko.api.v1.vision.VisionService.AnalyzeWineLabel:input_type -> stuko.api.v1.vision.AnalyzeWineLabelRequest
	1, // 3: stuko.api.v1.vision.VisionService.AnalyzeWineLabel:output_type -> stuko.api.v1.vision.AnalyzeWineLabelResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_v1_vision_proto_init() }
func file_api_proto_v1_vision_proto_init() {
	if File_api_proto_v1_vision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_vision_proto_rawDesc), len(file_api_proto_v1_vision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_vision_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_vision_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_vision_proto_msgTypes,
	}.Build()
	File_api_proto_v1_vision_proto = out.File
	file_api_proto_v1_vision_proto_goTypes = nil
	file_api_proto_v1_vision_proto_depIdxs = nil
}
